deployment:
  tasks:
    - export DEVDEPLOYPATH=/home/lucrhuof/dev.truyentv.vn/
    - export DEPLOYPATH=/home/lucrhuof/public_html/

    # Copy files, excluding the .git folder
    - /bin/cp -R --exclude='.git' ./ $DEPLOYPATH
    - /bin/cp -R --exclude='.git' ./ $DEVDEPLOYPATH
