deployment:
  tasks:
    - export DEVDEPLOYPATH=/home/lucrhuof/dev.truyentv.vn/
    - /bin/cp -R ./ $DEVDEPLOYPATH

    - export DEPLOYPATH=/home/lucrhuof/public_html/
    - /bin/cp -R ./ $DEPLOYPATH
