version: "3"
name: z-docker-compose
services:
    app:
        container_name: z-app
        build:
            context: ../.
            dockerfile: dockers/Dockerfile
        restart: always
        volumes:
            - ../:/var/www/html
        networks:
            - app_network
        depends_on:
            - mariadb
            - memcached

    nginx:
        image: nginx:latest
        container_name: z-nginx
        ports:
            - "8088:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ../:/var/www/html
        networks:
            - app_network
        depends_on:
            - app

    mariadb:
        image: mariadb:10
        container_name: z-mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: z_db
            MYSQL_USER: z_user
            MYSQL_PASSWORD: z_pass
        volumes:
            - z-db-volume:/var/lib/mysql
        networks:
            - app_network
        ports:
            - "3336:3306"

    memcached:
        image: memcached:latest
        container_name: z-memcached
        restart: always
        networks:
            - app_network
        ports:
            - "11214:11211"

volumes:
    z-db-volume:
        external: true

networks:
    app_network:
        driver: bridge
