version: '3'
name: z-docker-compose
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Web UI for viewing emails
      - "1025:1025"  # SMTP server
    networks:
        - app_network

networks:
    app_network:
        driver: bridge
